# Generated by Django 4.2.7 on 2023-12-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="deploy_test",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="테스트"
            ),
        ),
    ]
