# Generated by Django 4.2.7 on 2023-12-05 06:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_deploy_test"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="social_id",
        ),
    ]
