# Generated by Django 4.2.7 on 2023-12-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_user_social_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="deploy_test",
        ),
        migrations.AddField(
            model_name="user",
            name="social_id",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="소셜 아이디"
            ),
        ),
    ]
